sudo: required
services:
  - docker

before_install:
  - docker build -t vinodshalgar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run CI=true vinodshalgar/react-test npm test -- --coverage

after_success:
  - echo "after success started"
  - docker build -t vinodshalgar/multi-client ./client
  - docker build -t vinodshalgar/multi-nginx ./nginx
  - docker build -t vinodshalgar/multi-server ./server
  - docker build -t vinodshalgar/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
  - docker push vinodshalgar/multi-client
  - docker push vinodshalgar/multi-nginx
  - docker push vinodshalgar/multi-server
  - docker push vinodshalgar/multi-worker



